### ISSUE TITLE
Unexpected return object shape for schema extension function results in internal server error

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#191]
**What is the current behavior?**

Not returning a required argument in a schema extension function results in internal server error

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Example payload:

```graphql
type AuthenticateTwitterUserPayload {
  token: String!
  a: String!
}
```

Return data:

```js
return { data: { token: token } }
```

The required `a: String!` is missing in the response. Triggering this function results in an internal server error. Also, this will result in an internal server error:

```js
return { date: { token: token } }
```

Note `date` instead of `data`.

**Comment by marktani** [comment]
This is now fixed 🎉

**Comment by kbrandwijk** [comment]
@marktani How should this work now? I still get an internal error when the return shape is not right...

**Comment by marktani** [comment]
Thanks for opening https://github.com/graphcool/api-bugs/issues/224, let's keep track there :)
