### ISSUE TITLE
Problems with JSON validation

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#222]
# Introduction

Different problems around JSON validation. Start with this schema:

```graphql
type Post implements Node {
  json: Json
  createdAt: DateTime!
  id: ID! @isUnique
  isPublished: Boolean
  updatedAt: DateTime!
}
```

Each problem will be listed separately in the following section.

# Issues

## Creating invalid JSON

It's possible to create invalid JSON, for example like this:

```graphql
mutation createEntry($json: Json) {
  createPost(json: $json) {
    id
    __typename
    json
  }
}
```

```graphql
{"json":"{ \"a\": { \"b\": 1 }, \"c\": { \"d\": 2 } }"}
```

This creates a new node, which should not happen. An error message should be returned instead.

## Updating nodes with invalid JSON

Once invalid JSON is in the node, it's impossible to update it:

```graphql
mutation update {
  updatePost(id: "cj63mu6e8sqvc0131egr382t3" json: "{}") {
    json
  }
}
```

returns:

```json
{
  "data": {
    "updatePost": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 10,
          "column": 3
        }
      ],
      "path": [
        "updatePost"
      ],
      "code": 3037,
      "message": "The value in the field 'json' is not a valid Json: '\"{ \\\"a\\\": { \\\"b\\\": 1 }, \\\"c\\\": { \\\"d\\\": 2 } }\"'",
      "requestId": "simple:cj63mu9gs73bn0111m9wm76fa"
    }
  ]
}
```

The same behaviour is observed when a different field is updated:

```graphql
mutation update {
  updatePost(id: "cj63mu6e8sqvc0131egr382t3" isPublished: true) {
    json
  }
}
```

The update mutation should go through successfully, instead of returning a validation error.

## Deleting a node with invalid JSON

Deleting a node with invalid JSON deletes the node, but results in an internal server error:

```graphql
mutation del {
  deletePost(id: "cj63l28m3dwcl0134v4768heg") {
    id
  }
}
```

```json
{
  "data": {
    "deletePost": null
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Please contact us from the Console (https://console.graph.cool) or via email (support@graph.cool) and include your Request ID: simple:cj63n0u0t8j2h0134vzmi2v59",
      "requestId": "simple:cj63n0u0t8j2h0134vzmi2v59",
      "path": [
        "deletePost"
      ],
      "locations": [
        {
          "line": 16,
          "column": 3
        }
      ]
    }
  ]
}
```

The mutation should be executed (as is the case), and no error message should be returned.

# Workaround

A current workaround is to change the `Json` field to `String` instead - this is possible without data  loss and all the above problems don't occur anymore. However, this might require an update of client-side code, wherever the `Json` type is referenced, for example as a GraphQL variable.

**Comment by sorenbs** [comment]
There are two issues here. Only the second needs to be considered when fixing this:

1. We made an intentional change to the JSON type. It now only accepts objects and arrays as these are the only allowed top-level json constructs. Previously we would accept strings and simply store and return a string value. Some users did this and basically treaded the JSON field as a String field. These people are now in trouble.

2. The change we made is not complete. As documented in this ticket we still allow invalid JSON data in some cases. We should make sure that only `{}` and `[]` Json values are accepted.

**Comment by marktani** [comment]
All issues are now resolved: creating, updating and deleting nodes with invalid JSON is supported, while querying invalid JSON returns `null`, resulting in the GraphQL-characteristic "null-bubbling" if the field is required.

**Comment by LibanHassan** [comment]
Unfortunately the issue still exits. However I am able to delete nodes with the error I cannot update any of the fields. 
The JSON I have stored is of this form:`{"Monday":[
    { 
      "start":"2:30PM",
      "end":"7:30PM"
    }]}` 
I ran JSON.stringify on an object of that structure and ran my mutation. Now there is no way to update any of the affected node's fields.

**Comment by marktani** [comment]
Hey Liban, could you please reach out to support@graph.cool? Please include your project id and a mutation that reproduces your problem.

**Comment by marktani** [comment]
For reference, when using variables, instead of doing 

```js
const variables = {
  availability: JSON.stringify(this.state.availability)
}
```

you need to do 

```js
const variables = {
  availability: this.state.availability
}
```
