### ISSUE TITLE
Function works for mutation but not for nested mutation

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#67]
![functionwithmutation](https://cloud.githubusercontent.com/assets/1780597/26347174/ece14d36-3fa8-11e7-8c8d-ea3c9a74aaaa.png)

**Comment by joarwilk** [comment]
This looks like the same thing as #64

**Comment by marktani** [comment]
Hey @iamrommel and @joarwilk, this is now fixed 🙂

**Comment by barbatus** [comment]
@marktani I've just tried and still getting `Whoops. Looks like an internal server error` from the empty transform argument function

**Comment by barbatus** [comment]
while there is some progress: it's now launched at least according to logs

**Comment by marktani** [comment]
Hey @barbatus can you show your function and the corresponding mutation?

**Comment by barbatus** [comment]
@marktani  the function is the default one. mutation:
`mutation placeOrder(
$userId: ID!, $refillAt: Int!, $totalCost: Float!, $taxCost: Float!, $shipCost: Float!, $balance: Float!, $shopItems: [OrdershopItemsShopItem!], $bundleShopItems: [OrderbundleShopItemsBundleShopItem!],
$deliveryDate: DateTime!, $addressId: ID!, $cardDetailId: ID!) {
  createOrder(userId: $userId, refillAt: $refillAt, totalCost: $totalCost, taxCost: $taxCost, shipCost: 
                       $shipCost, balance: $balance, shopItems: $shopItems, bundleShopItems: 
                       $bundleShopItems, deliveryDate: $deliveryDate, shipAddressId: $addressId, 
                       cardDetailId: $cardDetailId) {
    id
    __typename
  }
}`

**Comment by marktani** [comment]
So on which triggers/hook points did you define the function? Potential triggers are:

* `Order is created`
* `ShopItem is created`
* `BundleShopItem is created`

And, just to be clear, your function looks like this I assume:

```js
module.exports = function (event) {
  console.log(event.data)
  return {data: event.data}
}
```

**Comment by barbatus** [comment]
@marktani `Order is created` on the transform argument step. You assume right about the function.

**Comment by marktani** [comment]
Thanks for the catch! This is indeed a different issue, the original issue posted here happened when the mutation where the function is defined on was the nested one.

I created a new issue here: #94.
