### ISSUE TITLE
Function in RP PRE_WRITE breaks some mutations

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#87]
Works:

```graphql
mutation{
  updateQuiz(
    id: "cj3czmwxvpg7j01650knboqcp", 
    behaviorsIds: []
  ){
    id
  }
}
```

```graphql
mutation{
  updateQuiz(
    id: "cj3czmwxvpg7j01650knboqcp", 
    status: IN_DEFINITION
  ){
    id
  }
}
```

Does not work:

```graphql
mutation{
  updateQuiz(
    id: "cj3czmwxvpg7j01650knboqcp", 
    behaviorsIds: []
    status: IN_DEFINITION
  ){
    id
  }
}
```

**Comment by adrianocola** [comment]
This also works (setting at least on item in the array):

```graphql
mutation{
  updateQuiz(
    id: "cj3czmwxvpg7j01650knboqcp", 
    behaviorsIds: ["cj3ae1lv48i460128xqx4rvp4"] 
    status: IN_DEFINITION
  ){
    id
  }
}
```

**Comment by marktani** [comment]
This is now fixed, thanks for the report @adrianocola 🙂

**Comment by adrianocola** [comment]
@marktani, I'm still getting this error. I'm executing this request:
```graphql
mutation{
  updateQuiz(
    id: "cj3czmwxvpg7j01650knboqcp", 
    behaviorsIds: []
    status: IN_DEFINITION
  ){
    id
  }
}
```

If I disable the function associated with the Quiz type (a `PRE_WRITE ` pipeline), it works. If I enable it the data is saved but my function is never called (and the server returns an error)

**Comment by marktani** [comment]
Hey @adrianocola can you share the error message?

**Comment by adrianocola** [comment]
```json
[
   {
      "data":{
         "updateQuiz":null
      },
      "errors":[
         {
            "message":"Whoops. Looks like an internal server error. Please contact us in Slack (https://slack.graph.cool) and send us your Request ID: cj3w0rj88duqr01387m2oc0s7",
            "requestId":"cj3w0rj88duqr01387m2oc0s7",
            "path":[
               "updateQuiz"
            ],
            "locations":[
               {
                  "line":2,
                  "column":3
               }
            ]
         }
      ]
   }
]
```

**Comment by marktani** [comment]
Wait you said before it's a `TRANSFORM_ARGUMENT` function, now it's a `PRE_WRITE` function. How does your function for `PRE_WRITE` look like?

**Comment by adrianocola** [comment]
You are right! I changed its type because I was not updating the data! 

My function only check if the status change is allowed (I get the current status from the DB, check if `OLD_STATUS -> NEW_STATUS` is a valid step and return the same data the function received if true). 

But I don't think the function implementation is the problem, because the function is not being called (I'm checking webtask logs).

I've created this `INLINE PRE_WRITE` function and it also gives the error (I also disabled my previous function):
```javascript
module.exports = function (event) {
  console.log(event.data)
  return {data: event.data}
}
```

`Whoops. Looks like an internal server error. Please contact us in Slack (https://slack.graph.cool) and send us your Request ID: cj3w1pgsdc5v101091g8te80r`

**Comment by marktani** [comment]
Thanks so much, we'll look into this! 🙌

**Comment by marktani** [comment]
A [very similar bug](https://github.com/graphcool/api-bugs/issues/175) has been fixed. Can you check if that issue still occurs, please?

**Comment by adrianocola** [comment]
Not happening anymore! Thank you @marktani!

**Comment by marktani** [comment]
Awesome, thanks for confirmation 💯
